/**
 * Push Notifications Configuration
 * 
 * VAPID Public Key Configuration
 * 
 * The VAPID public key is generated by your backend server.
 * Your backend should generate a public/private key pair using:
 * 
 * ```javascript
 * const webpush = require('web-push');
 * const vapidKeys = webpush.generateVAPIDKeys();
 * // vapidKeys.publicKey - use this in frontend
 * // vapidKeys.privateKey - keep this secret on backend
 * ```
 * 
 * The public key should be provided to the frontend (this file)
 * The private key should NEVER be exposed to the frontend
 */

// TODO: Replace with your actual VAPID public key from backend
// This should be a base64url encoded string
// Get this from your backend API or environment variable
export const VAPID_PUBLIC_KEY = "BMiAOnTpnmowrRvLGktV6uUx7ys5yDoeoNA0-jgy92nH9rvQ5FGr4lruS9vdHHziyxK_njbB911GrFIkufKluJ4";

// Contact email for VAPID subject (sub) field
// This is used when backend sends push messages
export const VAPID_CONTACT_EMAIL = "sportverse.co@gmail.com";

